# Generated by Django 4.2.1 on 2023-06-06 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("todolist", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todolist",
            options={"verbose_name": "Список дел", "verbose_name_plural": "Списки дел"},
        ),
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=64, verbose_name="Заголовок дела"),
                ),
                (
                    "todo_date",
                    models.DateField(null=True, verbose_name="Дата исполнения"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("В", "Высший приоритет"),
                            ("С", "Средний приоритет"),
                            ("Н", "Низший приоритет"),
                        ],
                        default="В",
                        max_length=2,
                        verbose_name="Приоритет",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "complete_date",
                    models.DateField(null=True, verbose_name="Дата исполнения"),
                ),
                (
                    "fk_todo_todolist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="todolist.todolist",
                    ),
                ),
            ],
        ),
    ]
