# Generated by Django 4.2.1 on 2023-06-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todolist", "0002_alter_todolist_options_todo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todo",
            options={"verbose_name": "задача", "verbose_name_plural": "задачи"},
        ),
        migrations.AlterField(
            model_name="todo",
            name="complete_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата исполнения"
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="todo_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата исполнения"
            ),
        ),
    ]
