# Generated by Django 4.2.1 on 2023-06-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todolist", "0003_alter_todo_options_alter_todo_complete_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todo",
            options={
                "ordering": (
                    "-complete_date",
                    "fk_todo_todolist",
                    "priority",
                    "todo_date",
                ),
                "verbose_name": "задача",
                "verbose_name_plural": "задачи",
            },
        ),
        migrations.AlterField(
            model_name="todo",
            name="priority",
            field=models.IntegerField(
                choices=[
                    (1, "Высший приоритет"),
                    (2, "Средний приоритет"),
                    (3, "Низший приоритет"),
                ],
                default=1,
                verbose_name="Приоритет",
            ),
        ),
    ]
