# Generated by Django 4.2.1 on 2023-06-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todolist", "0004_alter_todo_options_alter_todo_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="priority",
            field=models.IntegerField(
                choices=[
                    (1, "Высший приоритет"),
                    (2, "Средний приоритет"),
                    (3, "Низший приоритет"),
                ],
                default=1,
                null=True,
                verbose_name="Приоритет",
            ),
        ),
    ]
